version: '3'
services:
  server:
    container_name: NODEJS_SERVER_TEST
    build: '.'
    volumes: 
      - .:/usr/src/app
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    command: bash -c "npm run start"